// ⚠️ This file is auto-generated by Scripts/GenerateStrings.swift
// Do not edit manually. Run `make strings` to regenerate.

import Foundation

// MARK: - Bundle

private final class FinderBundleToken {}

extension Bundle {
  static let finderFeature = Bundle(for: FinderBundleToken.self)
}

// MARK: - FinderStrings

enum FinderStrings {
  // MARK: - Accessibility

  /// Menu
  static var accessibilityMenu: String {
    String(localized: "finder.accessibility.menu", bundle: .finderFeature)
  }

  // MARK: - Alert

  /// Cancel
  static var alertCancel: String {
    String(localized: "finder.alert.cancel", bundle: .finderFeature)
  }

  /// Create
  static var alertCreate: String {
    String(localized: "finder.alert.create", bundle: .finderFeature)
  }

  /// Delete
  static var alertDeleteAction: String {
    String(localized: "finder.alert.delete.action", bundle: .finderFeature)
  }

  /// Delete %lld items?
  static func alertDeleteMessageMultiple(_ arg0: Int) -> String {
    String(localized: "finder.alert.delete.message_multiple \(arg0)", bundle: .finderFeature)
  }

  /// Delete %@?
  static func alertDeleteMessageSingle(_ arg0: String) -> String {
    String(localized: "finder.alert.delete.message_single \(arg0)", bundle: .finderFeature)
  }

  /// Delete
  static var alertDeleteTitle: String {
    String(localized: "finder.alert.delete.title", bundle: .finderFeature)
  }

  /// Error
  static var alertErrorTitle: String {
    String(localized: "finder.alert.error.title", bundle: .finderFeature)
  }

  /// Folder Name
  static var alertNewFolderPlaceholder: String {
    String(localized: "finder.alert.new_folder.placeholder", bundle: .finderFeature)
  }

  /// New Folder
  static var alertNewFolderTitle: String {
    String(localized: "finder.alert.new_folder.title", bundle: .finderFeature)
  }

  /// OK
  static var alertOk: String {
    String(localized: "finder.alert.ok", bundle: .finderFeature)
  }

  /// Rename
  static var alertRenameTitle: String {
    String(localized: "finder.alert.rename.title", bundle: .finderFeature)
  }

  // MARK: - Cell

  static func cellItemCount(_ arg0: Int) -> String {
    String(localized: "finder.cell.item_count \(arg0)", bundle: .finderFeature)
  }

  // MARK: - Dir Selection

  /// Move Here
  static var dirSelectionMoveHere: String {
    String(localized: "finder.dir_selection.move_here", bundle: .finderFeature)
  }

  // MARK: - Edit

  /// Deselect All
  static var editDeselectAll: String {
    String(localized: "finder.edit.deselect_all", bundle: .finderFeature)
  }

  /// Select All
  static var editSelectAll: String {
    String(localized: "finder.edit.select_all", bundle: .finderFeature)
  }

  /// Select items to delete
  static var editSelectToDelete: String {
    String(localized: "finder.edit.select_to_delete", bundle: .finderFeature)
  }

  /// Select items to move
  static var editSelectToMove: String {
    String(localized: "finder.edit.select_to_move", bundle: .finderFeature)
  }

  // MARK: - Menu

  /// Create Directory
  static var menuCreateDirectory: String {
    String(localized: "finder.menu.create_directory", bundle: .finderFeature)
  }

  /// Date
  static var menuDate: String {
    String(localized: "finder.menu.date", bundle: .finderFeature)
  }

  /// Delete
  static var menuDelete: String {
    String(localized: "finder.menu.delete", bundle: .finderFeature)
  }

  /// Document
  static var menuDocument: String {
    String(localized: "finder.menu.document", bundle: .finderFeature)
  }

  /// Move
  static var menuMove: String {
    String(localized: "finder.menu.move", bundle: .finderFeature)
  }

  /// Name
  static var menuName: String {
    String(localized: "finder.menu.name", bundle: .finderFeature)
  }

  /// New Folder
  static var menuNewFolder: String {
    String(localized: "finder.menu.new_folder", bundle: .finderFeature)
  }

  /// Preview
  static var menuPreview: String {
    String(localized: "finder.menu.preview", bundle: .finderFeature)
  }

  /// Rename
  static var menuRename: String {
    String(localized: "finder.menu.rename", bundle: .finderFeature)
  }

  /// Select
  static var menuSelect: String {
    String(localized: "finder.menu.select", bundle: .finderFeature)
  }

  /// Share
  static var menuShare: String {
    String(localized: "finder.menu.share", bundle: .finderFeature)
  }

  /// Size
  static var menuSize: String {
    String(localized: "finder.menu.size", bundle: .finderFeature)
  }

  /// Sort
  static var menuSort: String {
    String(localized: "finder.menu.sort", bundle: .finderFeature)
  }

  // MARK: - Search

  /// Search
  static var searchPlaceholder: String {
    String(localized: "finder.search.placeholder", bundle: .finderFeature)
  }

  // MARK: - Section

  /// Directories
  static var sectionDirectories: String {
    String(localized: "finder.section.directories", bundle: .finderFeature)
  }

  /// Files
  static var sectionFiles: String {
    String(localized: "finder.section.files", bundle: .finderFeature)
  }

  // MARK: - State

  /// ascending
  static var stateAscending: String {
    String(localized: "finder.state.ascending", bundle: .finderFeature)
  }

  /// descending
  static var stateDescending: String {
    String(localized: "finder.state.descending", bundle: .finderFeature)
  }

  /// Documents
  static var stateTitle: String {
    String(localized: "finder.state.title", bundle: .finderFeature)
  }
}
