disabled_rules: # rule identifiers to exclude from running
- attributes
- line_length
- function_parameter_count
- non_optional_string_data_conversion
- identifier_name
- trailing_newline
- cyclomatic_complexity
- trailing_whitespace
- file_length
- type_body_length
- function_body_length
opt_in_rules: # some rules are only opt-in
- empty_count
- attributes
- closure_spacing
# Find all the available rules by running:
# swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
- ../Projects/
excluded: # paths to ignore during linting. Takes precedence over `included`.
