// ⚠️ This file is auto-generated by Scripts/GenerateStrings.swift
// Do not edit manually. Run `make strings` to regenerate.

import Foundation

// MARK: - Bundle

private final class SharedUIBundleToken {}

extension Bundle {
  static let sharedUIComponents = Bundle(for: SharedUIBundleToken.self)
}

// MARK: - SharedStrings

enum SharedStrings {
  // MARK: - Empty

  /// Error occurred
  static var emptyErrorMessage: String {
    String(localized: "shared.empty.error.message", bundle: .sharedUIComponents)
  }

  /// There's nothing here yet.
  static var emptyNoDataDescription: String {
    String(localized: "shared.empty.no_data.description", bundle: .sharedUIComponents)
  }

  /// No Data
  static var emptyNoDataMessage: String {
    String(localized: "shared.empty.no_data.message", bundle: .sharedUIComponents)
  }

  /// No matches for your search.
  static var emptyNoSearchResultsDescription: String {
    String(localized: "shared.empty.no_search_results.description", bundle: .sharedUIComponents)
  }

  /// No Search Results
  static var emptyNoSearchResultsMessage: String {
    String(localized: "shared.empty.no_search_results.message", bundle: .sharedUIComponents)
  }
}
