// ⚠️ This file is auto-generated by Scripts/GenerateStrings.swift
// Do not edit manually. Run `make strings` to regenerate.

import Foundation

// MARK: - Bundle

private final class ReaderBundleToken {}

extension Bundle {
  static let readerFeature = Bundle(for: ReaderBundleToken.self)
}

// MARK: - ReaderStrings

enum ReaderStrings {
  // MARK: - Alert

  /// Cancel
  static var alertCancel: String {
    String(localized: "reader.alert.cancel", bundle: .readerFeature)
  }

  /// Go
  static var alertGo: String {
    String(localized: "reader.alert.go", bundle: .readerFeature)
  }

  /// Enter page number (1-%lld)
  static func alertGoToPageMessage(_ arg0: Int) -> String {
    String(localized: "reader.alert.go_to_page.message \(arg0)", bundle: .readerFeature)
  }

  /// Page number
  static var alertGoToPagePlaceholder: String {
    String(localized: "reader.alert.go_to_page.placeholder", bundle: .readerFeature)
  }

  /// Go to Page
  static var alertGoToPageTitle: String {
    String(localized: "reader.alert.go_to_page.title", bundle: .readerFeature)
  }

  // MARK: - Setting

  /// Content Mode
  static var settingRowContentMode: String {
    String(localized: "reader.setting.row.content_mode", bundle: .readerFeature)
  }

  /// Direction
  static var settingRowDirection: String {
    String(localized: "reader.setting.row.direction", bundle: .readerFeature)
  }

  /// Display
  static var settingRowDisplay: String {
    String(localized: "reader.setting.row.display", bundle: .readerFeature)
  }

  /// Image Filter
  static var settingRowImageFilter: String {
    String(localized: "reader.setting.row.image_filter", bundle: .readerFeature)
  }

  /// Transition
  static var settingRowTransition: String {
    String(localized: "reader.setting.row.transition", bundle: .readerFeature)
  }

  /// Wide Page Splitting
  static var settingRowWidePageSplitting: String {
    String(localized: "reader.setting.row.wide_page_splitting", bundle: .readerFeature)
  }

  /// General
  static var settingSectionGeneral: String {
    String(localized: "reader.setting.section.general", bundle: .readerFeature)
  }

  /// Image
  static var settingSectionImage: String {
    String(localized: "reader.setting.section.image", bundle: .readerFeature)
  }

  /// Viewer Settings
  static var settingTitle: String {
    String(localized: "reader.setting.title", bundle: .readerFeature)
  }

  // MARK: - Segment Items

  /// Aspect Fit, Aspect Fill, Scroll to Fit
  static var contentModeItems: [String] {
    [
      String(localized: "reader.setting.content_mode.0_aspect_fit", bundle: .readerFeature),
      String(localized: "reader.setting.content_mode.1_aspect_fill", bundle: .readerFeature),
      String(localized: "reader.setting.content_mode.2_scroll_to_fit", bundle: .readerFeature)
    ]
  }

  /// None, Cut, Cut & Reverse
  static var cutModeItems: [String] {
    [
      String(localized: "reader.setting.cut_mode.0_none", bundle: .readerFeature),
      String(localized: "reader.setting.cut_mode.1_cut", bundle: .readerFeature),
      String(localized: "reader.setting.cut_mode.2_cut_and_reverse", bundle: .readerFeature)
    ]
  }

  /// To Right, To Left, To Bottom
  static var directionItems: [String] {
    [
      String(localized: "reader.setting.direction.0_to_right", bundle: .readerFeature),
      String(localized: "reader.setting.direction.1_to_left", bundle: .readerFeature),
      String(localized: "reader.setting.direction.2_to_bottom", bundle: .readerFeature)
    ]
  }

  /// Single, Double
  static var displayItems: [String] {
    [
      String(localized: "reader.setting.display.0_single", bundle: .readerFeature),
      String(localized: "reader.setting.display.1_double", bundle: .readerFeature)
    ]
  }

  /// None, Contrast, Inverted, Grayscale
  static var filterItems: [String] {
    [
      String(localized: "reader.setting.filter.0_none", bundle: .readerFeature),
      String(localized: "reader.setting.filter.1_contrast", bundle: .readerFeature),
      String(localized: "reader.setting.filter.2_inverted", bundle: .readerFeature),
      String(localized: "reader.setting.filter.3_grayscale", bundle: .readerFeature)
    ]
  }

  /// Paging, Page Curl, Scroll, None
  static var transitionItems: [String] {
    [
      String(localized: "reader.setting.transition.0_paging", bundle: .readerFeature),
      String(localized: "reader.setting.transition.1_page_curl", bundle: .readerFeature),
      String(localized: "reader.setting.transition.2_scroll", bundle: .readerFeature),
      String(localized: "reader.setting.transition.3_none", bundle: .readerFeature)
    ]
  }
}
