//
//  DirPickerViewController.swift
//  LightComicsV2
//
//  Created by LeeSeGun on 2021/12/23.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DirPickerDisplayLogic: AnyObject {
    func displaySomething(viewModel: DirPicker.Something.ViewModel)
}

class DirPickerViewController: UITableViewController, DirPickerDisplayLogic {
    var interactor: DirPickerBusinessLogic?
    var router: (NSObjectProtocol & DirPickerRoutingLogic & DirPickerDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = DirPickerInteractor()
        let presenter = DirPickerPresenter()
        let router = DirPickerRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configureTableView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
    
    
    // MARK: - UI Configurations
    private func configureTableView() {
        tableView.separatorStyle = .singleLine
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "A")
        tableView.allowsMultipleSelectionDuringEditing = true
    }
    
    
    
    
    func displaySomething(viewModel: DirPicker.Something.ViewModel) {
        
    }
    
}
