//
//  FinderWorker.swift
//  LightComicsV2
//
//  Created by LeeSeGun on 2021/12/20.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FileKit

class FinderWorker {
    
    init() {
//        makeSampleFiles()
    }
    
    func makeSampleFiles() {
        let path = Path.userDocuments
        for i in 0...4 {
            let dirPath = path + "Dir \(i)"
            try? dirPath.createDirectory()
        }

        for i in 0...4 {
            let dirPath = path + "File \(i).txt"
            try? dirPath.createFile()
        }
    }
    
    func makeDirectory(in parent: Path, dirName: String) throws {
        let new = parent + dirName
        try new.createDirectory()
    }
    
    
    /// 요청 경로에 자식들을 반환한다.
    /// - Parameters:
    ///   - request: Finder.FetchElements.Request
    ///   - completion: completion description
    func fetchPathElements(request: Finder.FetchFiles.Request, completion: @escaping ([Path]) -> Void) {
        completion(request.path.children())
    }
}
/*
 코어데이터나 서버와 통신이 필요할 경우, Interactor에서 처리하는 것이 아닌 Worker에서 처리하도록 분리할 수 있다.
 Worker에서 필요한 값을 fetch한 후에 Interactor로 넘겨주게 된다.
 외부 라이브러리를 사용해야 하는 경우 Worker로 빼두어야 한다.
 */
