//
//  FinderPresenter.swift
//  LightComicsV2
//
//  Created by LeeSeGun on 2021/12/20.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FileKit

protocol FinderPresentationLogic {
    func presentFiles(response: Finder.FetchFiles.Response)
}

class FinderPresenter: FinderPresentationLogic {
    weak var viewController: FinderDisplayLogic?

    
    // MARK: Present Files
    func presentFiles(response: Finder.FetchFiles.Response) {
        
        var dirs: [Path] = []
        var files: [Path] = []
        response.elements.forEach { p in
            if p.isDirectory { dirs.append(p) }
            else { files.append(p) }
        }
        
        dirs.sort()
        files.sort()
        
        let viewModel = Finder.FetchFiles.ViewModel(directories: dirs, files: files)
        viewController?.displayFiles(viewModel: viewModel)
    }
    
}
